language: ruby
rvm:
  - 2.5.5
env: 
  - "S3_KEY=TEST S3_SECRET=TEST"
before_install:
  - gem install -v 1.17.3 bundler --no-rdoc --no-ri
before_script:
  - psql -c 'create database bestofama_test;' -U postgres
  - bundle exec rake db:schema:load
script: bundle exec rspec
