language: ruby
rvm:
  - 2.1.1
env: 
	- "S3_KEY=TEST"
	- "S3_SECRET=TEST"
before_script:
  - psql -c 'create database bestofama_test;' -U postgres
  - bundle exec rake db:schema:load
script: bundle exec rspec
