source 'https://rubygems.org'

gem 'rails', '3.2.10'
gem 'pg'
#gem 'sqlite3'
gem 'thin'
gem 'jquery-rails'
gem 'authlogic'
gem 'will_paginate'
gem 'bootstrap-will_paginate'
gem 'wikipedia-client'
gem 'high_voltage'
gem 'acts-as-taggable-on'
gem 'htmlentities'
gem 'awesome_print'
gem 'sitemap_generator', '~> 3.4'
gem 'carrierwave'
gem 'fog'
gem 'newrelic_rpm'
gem 'memcachier'
gem 'dalli'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
