development:
  adapter: postgresql
  encoding: unicode
  database: bestofama_development
  host: localhost
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: bestofama_test
  host: localhost
  pool: 5
  username: postgres
  password: password
